import { z } from "zod";

import type { VisibilityCrewAnalysis } from "@/lib/visibility/crew/types";

const url = z.string().url();
const stakes = z.enum(["critical", "high", "medium", "low"]);
const confidence = z.enum(["high", "medium", "insufficient"]);

const responseSchema = z.object({
  analysis_id: z.string().min(8).max(120),
  project_id: z.string().min(8).max(120),
  status: z.enum(["completed", "insufficient_evidence"]),
  model_runtime: z.string().min(1).max(200),
  prompt_version: z.string().min(1).max(200),
  executive_headline: z.string().min(5).max(240),
  executive_summary: z.string().min(5).max(1_600),
  primary_risk: z.string().max(1_000).nullable().default(null),
  findings: z.array(z.object({
    prompt_id: z.string(),
    buyer_job: z.string(),
    finding: z.string(),
    stakes,
    evidence_run_ids: z.array(z.string()),
    source_urls: z.array(url),
    uncertainty: z.string().nullable().default(null),
  })).max(20),
  customer_pain_themes: z.array(z.object({
    pain: z.string(),
    evidence_type: z.enum(["observed", "inferred"]),
    implication: z.string(),
    affected_prompt_ids: z.array(z.string()).min(1),
    evidence_run_ids: z.array(z.string()).min(1),
  })).max(10),
  brand_voice: z.array(z.object({
    dimension: z.enum(["accuracy", "completeness", "differentiation", "trust", "risk"]),
    observed: z.string(),
    intended: z.string(),
    status: z.enum(["aligned", "partial", "misaligned", "insufficient_evidence"]),
    evidence_run_ids: z.array(z.string()),
  })).max(10),
  executive_decisions: z.array(z.object({
    audience: z.enum(["ceo", "cfo", "product", "marketing"]),
    decision: z.string(),
    value_case: z.string(),
    risk_if_ignored: z.string(),
    evidence_run_ids: z.array(z.string()).min(1),
    source_urls: z.array(url),
    confidence,
  })).max(4),
  actions: z.array(z.object({
    title: z.string(),
    why_now: z.string(),
    owner: z.enum(["seo", "content", "pr", "web", "product_marketing"]),
    effort: z.enum(["low", "medium", "high"]),
    stakes,
    business_outcome: z.enum(["demand_capture", "conversion", "retention", "trust", "risk_reduction"]),
    decision_makers: z.array(z.enum(["ceo", "cfo", "product", "marketing"])).min(1).max(4),
    value_hypothesis: z.string(),
    cost_of_inaction: z.string(),
    impact_horizon: z.enum(["now", "this_quarter", "strategic"]),
    evidence_thesis: z.string(),
    alternatives_considered: z.array(z.string()).min(1).max(5),
    do_not_do: z.array(z.string()).min(1).max(5),
    falsification_rule: z.string(),
    linked_page_url: url,
    acceptance_criteria: z.array(z.string()).min(1).max(8),
    retest_rule: z.string(),
    affected_prompt_ids: z.array(z.string()).min(1),
    evidence_run_ids: z.array(z.string()).min(1),
    source_urls: z.array(url),
    confidence,
  })).max(10),
  limitations: z.array(z.string()).max(12),
}).strict();

export function parseVisibilityCrewAnalysis(input: unknown): VisibilityCrewAnalysis {
  const value = responseSchema.parse(input);
  return {
    analysisId: value.analysis_id,
    projectId: value.project_id,
    status: value.status,
    modelRuntime: value.model_runtime,
    promptVersion: value.prompt_version,
    executiveHeadline: value.executive_headline,
    executiveSummary: value.executive_summary,
    primaryRisk: value.primary_risk,
    findings: value.findings.map((finding) => ({
      promptId: finding.prompt_id,
      buyerJob: finding.buyer_job,
      finding: finding.finding,
      stakes: finding.stakes,
      evidenceRunIds: finding.evidence_run_ids,
      sourceUrls: finding.source_urls,
      uncertainty: finding.uncertainty,
    })),
    customerPainThemes: value.customer_pain_themes.map((pain) => ({
      pain: pain.pain,
      evidenceType: pain.evidence_type,
      implication: pain.implication,
      affectedPromptIds: pain.affected_prompt_ids,
      evidenceRunIds: pain.evidence_run_ids,
    })),
    brandVoice: value.brand_voice.map((finding) => ({
      dimension: finding.dimension,
      observed: finding.observed,
      intended: finding.intended,
      status: finding.status,
      evidenceRunIds: finding.evidence_run_ids,
    })),
    executiveDecisions: value.executive_decisions.map((decision) => ({
      audience: decision.audience,
      decision: decision.decision,
      valueCase: decision.value_case,
      riskIfIgnored: decision.risk_if_ignored,
      evidenceRunIds: decision.evidence_run_ids,
      sourceUrls: decision.source_urls,
      confidence: decision.confidence,
    })),
    actions: value.actions.map((action) => ({
      title: action.title,
      whyNow: action.why_now,
      owner: action.owner,
      effort: action.effort,
      stakes: action.stakes,
      businessOutcome: action.business_outcome,
      decisionMakers: action.decision_makers,
      valueHypothesis: action.value_hypothesis,
      costOfInaction: action.cost_of_inaction,
      impactHorizon: action.impact_horizon,
      evidenceThesis: action.evidence_thesis,
      alternativesConsidered: action.alternatives_considered,
      doNotDo: action.do_not_do,
      falsificationRule: action.falsification_rule,
      linkedPageUrl: action.linked_page_url,
      acceptanceCriteria: action.acceptance_criteria,
      retestRule: action.retest_rule,
      affectedPromptIds: action.affected_prompt_ids,
      evidenceRunIds: action.evidence_run_ids,
      sourceUrls: action.source_urls,
      confidence: action.confidence,
    })),
    limitations: value.limitations,
  };
}
